package coupon.mock;

import java.util.ArrayList;
import java.util.List;

import coupon.coupon.domain.Coupon;
import coupon.member.domain.Member;
import coupon.membercoupon.domain.MemberCoupon;
import coupon.membercoupon.service.port.MemberCouponRepository;

public class FakeMemberCouponRepository implements MemberCouponRepository {

    public final List<MemberCoupon> storage = new ArrayList<>();
    private Long autoGeneratedId = 0L;

    @Override
    public int countByMemberAndCoupon(final Member member, final Coupon coupon) {
        return 0;
    }

    @Override
    public void save(final MemberCoupon memberCoupon) {
        if (memberCoupon.getId() == null || memberCoupon.getId() == 0) {
            storage.add(new MemberCoupon(
                    ++autoGeneratedId,
                    memberCoupon.getMember(),
                    memberCoupon.getCoupon(),
                    memberCoupon.isUsed(),
                    memberCoupon.getCreatedAt(),
                    memberCoupon.getExpiredAt()
            ));
        } else {
            storage.add(memberCoupon);
        }
    }

    @Override
    public List<MemberCoupon> findAllByMember(final Member member) {
        return storage.stream()
                .filter(memberCoupon -> memberCoupon.getMember().equals(member))
                .toList();
    }
}
